# Generated by Django 3.1.3 on 2021-05-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.TextField()),
                ('nombre_paciente', models.TextField()),
                ('tipo_prevision', models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Ninguna', 'Ninguna')], max_length=50)),
                ('nombre_medico', models.TextField()),
                ('especialidad', models.CharField(choices=[('Cirugía', 'Cirugía'), ('Cardiología', 'Cardiología'), ('Odontología', 'Odontología'), ('Pediatría', 'Pediatría'), ('Ginecología', 'Ginecología'), ('Oftomología', 'Oftomología')], max_length=50)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.TextField()),
                ('tipo_Especialidad', models.CharField(choices=[('Cirugía', 'Cirugía'), ('Cardiología', 'Cardiología'), ('Odontología', 'Odontología'), ('Pediatría', 'Pediatría'), ('Ginecología', 'Ginecología'), ('Oftomología', 'Oftomología')], max_length=50)),
            ],
        ),
    ]
