# Generated by Django 3.1.3 on 2021-05-21 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.TextField()),
                ('tipo_Especialidad', models.CharField(choices=[('Cirugía', 'Cirugía'), ('Cardiología', 'Cardiología'), ('Odontología', 'Odontología'), ('Pediatría', 'Pediatría'), ('Ginecología', 'Ginecología'), ('Oftomología', 'Oftomología')], max_length=50)),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
