# Generated by Django 2.2.23 on 2021-05-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='nombre_medico',
            field=models.TextField(max_length=30),
        ),
    ]
