# Generated by Django 3.1.1 on 2021-05-30 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0002_auto_20210521_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='medico',
        ),
        migrations.AddField(
            model_name='citamedica',
            name='nombre_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medico.medico'),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='hora_cita',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre_medico',
            field=models.TextField(),
        ),
    ]
