# Generated by Django 3.1.1 on 2021-05-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0003_auto_20210529_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.TextField()),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='citamedica',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='tipo_Especialidad',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medico.especialidad'),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medico.especialidad'),
        ),
    ]
