# Generated by Django 2.2.23 on 2021-05-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0003_citamedica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='autor_id',
        ),
    ]
