# Generated by Django 3.1.1 on 2021-05-30 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0004_auto_20210530_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='precio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precio', to='Medico.especialidad'),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidad', to='Medico.especialidad'),
        ),
    ]
