# Generated by Django 2.2.23 on 2021-05-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0004_remove_medico_autor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='hora_cita',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='fecha_cita',
            field=models.Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='tipo_prevision',
            field=models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Ninguna', 'Ninguna')], max_length=50),
        ),
    ]
