# Generated by Django 3.1.1 on 2021-06-01 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0006_remove_citamedica_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='nombre_medico',
        ),
        migrations.AddField(
            model_name='citamedica',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='Medico.medico'),
        ),
    ]
