# Generated by Django 3.1.1 on 2021-06-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0008_auto_20210531_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='run',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
