# Generated by Django 3.1.3 on 2021-06-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('run', models.TextField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.TextField()),
                ('tipo_prevision', models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Ninguna', 'Ninguna')], max_length=50)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidad', to='Medico.especialidad')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='Medico.medico')),
            ],
        ),
    ]
